name: CI

on: [push,pull_request]

jobs:
  BuildAndPack:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: dotnet build FontStashSharp.sln --configuration Release

    - name: Test
      run: dotnet test FontStashSharp.sln

    - name: Pack
      run: dotnet pack src/FontStashSharp/FontStashSharp.FNA.NET.csproj

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }} Artifacts
        path: |
          src/FontStashSharp/bin/Release/*.nupkg